site_name: serp connect api
pages:
    - Home: index.md
    - 'User Guide':
        - Development: 'user-guide/development.md'
        - Contributing: 'user-guide/contributing.md'
        - Testing: 'user-guide/testing.md'
    - 'Internals':
        - 'Trust Levels': 'internals/trust.md'
        - 'Sessions': 'internals/sessions.md'
    - API: api.md
theme: readthedocs
